version: '3.8'

services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  service:
    build:
      context: service
      dockerfile: Dockerfile
    ports:
      - '8080:8080'